name: f_note
description: "一款支持Markdown和LaTex的的笔记软件"
publish_to: 'none' 

version: 1.1.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown_latex: ^0.3.4
  path_provider: ^2.1.5
  provider: ^6.0.5
  file_picker: ^5.2.5
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
